services:
  marimo-in-snowflake:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${SNOWFLAKE_ACCOUNT}.registry.snowflakecomputing.com/${SNOWFLAKE_DATABASE}/${SNOWFLAKE_SCHEMA}/${SNOWFLAKE_IMAGE_REPOSTORY}/marimo-notebook:latest
    container_name: marimo-notebook
    ports:
      - "2718:2718"
    restart: unless-stopped
