[project]
name = "marimo-spcs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "marimo>=0.15.0",
    "snowflake>=1.7.0",
    "snowflake-cli>=3.7.0",
    "snowflake-snowpark-python>=1.37.0",
]
